package pe.edu.upn.educaapp.view;

import javax.swing.JInternalFrame;

public class MainView extends javax.swing.JFrame {

    public MainView() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        exitMenuItem = new javax.swing.JMenuItem();
        menuProcesos = new javax.swing.JMenu();
        menuProcesosMatricular = new javax.swing.JMenuItem();
        menuConsultas = new javax.swing.JMenu();
        menuConsultasMatriculados = new javax.swing.JMenuItem();
        menuReportes = new javax.swing.JMenu();
        menuReporteIngresos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EDUCA APP");

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(this::exitMenuItemActionPerformed);
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        menuProcesos.setText("Procesos");

        menuProcesosMatricular.setText("Matricular");
        menuProcesosMatricular.addActionListener(this::menuProcesosMatricularActionPerformed);
        menuProcesos.add(menuProcesosMatricular);

        menuBar.add(menuProcesos);

        menuConsultas.setText("Consultas");

        menuConsultasMatriculados.setText("Matriculados");
        menuConsultasMatriculados.addActionListener(this::menuConsultasMatriculadosActionPerformed);
        menuConsultas.add(menuConsultasMatriculados);

        menuBar.add(menuConsultas);

        menuReportes.setText("Reportes");

        menuReporteIngresos.setText("Ingresos");
        menuReporteIngresos.addActionListener(this::menuReporteIngresosActionPerformed);
        menuReportes.add(menuReporteIngresos);

        menuBar.add(menuReportes);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void menuProcesosMatricularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProcesosMatricularActionPerformed
        /*JInternalFrame view = new ProcesoMatricularView();
        desktopPane.add(view);
        view.setVisible(true);*/
         this.mostrarForm(ProcesoMatricularView.class);
    }//GEN-LAST:event_menuProcesosMatricularActionPerformed

    private void menuConsultasMatriculadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConsultasMatriculadosActionPerformed
        /*JInternalFrame view = new ConsultaMatriculadosView();
        desktopPane.add(view);
        view.setVisible(true);*/
        this.mostrarForm(ConsultaMatriculadosView.class);
    }//GEN-LAST:event_menuConsultasMatriculadosActionPerformed

    private void menuReporteIngresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReporteIngresosActionPerformed
        /*JInternalFrame view = new ReporteIngresosView();
        desktopPane.add(view);
        view.setVisible(true);*/
        this.mostrarForm(ReporteIngresosView.class);
    }//GEN-LAST:event_menuReporteIngresosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuConsultas;
    private javax.swing.JMenuItem menuConsultasMatriculados;
    private javax.swing.JMenu menuProcesos;
    private javax.swing.JMenuItem menuProcesosMatricular;
    private javax.swing.JMenuItem menuReporteIngresos;
    private javax.swing.JMenu menuReportes;
    // End of variables declaration//GEN-END:variables

    private void mostrarForm(Class<?> aClass) {
        try {
            // Variable de control
            JInternalFrame view = null;
            // Buscar instancia
            for (JInternalFrame form : desktopPane.getAllFrames()) {
                if (aClass.isInstance(form)) {
                    view = form;
                    break;
                }
            }
            // Crear instancia
            if (view == null) {
                //view = (JInternalFrame) Class.forName(aClass.getName()).newInstance();
                view = (JInternalFrame) aClass.getConstructor().newInstance();
                desktopPane.add(view);
                view.setVisible(true);
                view.setMaximum(true);
            }
            view.setSelected(true);
        } catch (Exception e) {
        }
    }

}
